TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  - KEY: KEY_CAPSLOCK
    TAP: KEY_ESC
    HOLD: KEY_RIGHTCTRL

  - KEY: KEY_LEFTSHIFT
    TAP: KEY_TAB
    HOLD: KEY_LEFTSHIFT

  - KEY: KEY_RIGHTALT
    TAP: KEY_RIGHTALT
    HOLD: KEY_LEFTMETA

  - KEY: KEY_LEFTCTRL
    TAP: KEY_LEFTCTRL
    HOLD: KEY_BACKSPACE

  - KEY: KEY_LEFTALT
    TAP: KEY_BACKSPACE
    HOLD: KEY_LEFTALT

