alias up='doas xbps-install -Su'
alias i='doas xbps-install'
alias r='doas xbps-remove'
alias orphans='doas xbps-remove -oO'
alias vp='./xbps-src pkg'
alias ivp='xbps-install --repository hostdir/binpkgs'
