#!/bin/bash

to_study=$1

open() {
  echo $1
  alacritty -t 'anki-vim' -e anki-vim -e nvim $1
}

notify() {
  notify-send.py -t 1300 --replaces-process anki -u low $1
}

anki_vim() {
  notify $1
  open $1
}

case $to_study in
  p)
    anki_vim 'Portuguese'
    ;;
  e)
    anki_vim 'English'
    ;;
  c)
    anki_vim 'Code'
    ;;
  *)
    notify-send 'Not found!'
    ;;
  esac
