#!/bin/sh

# If you use pywal, you need to restore the scheme here
# (cat ~/.cache/wal/sequences &)

export NNN_BMS="D:$HOME/Downloads;v:$HOME/Videos"
export NNN_COLORS="5236"
export NNN_SSHFS="sshfs -o follow_symlinks"        # make sshfs follow symlinks on the remote
export NNN_TRASH=1                                 # trash (needs trash-cli) instead of delete

alias nsel="cat ${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection | tr '\0' '\n'"

# To use a CLI opener, specify the `-c` option to `nnn`
# export NNN_OPENER="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/nuke"

# Unmask ^Q (if required, see `stty -a`) to Quit nnn
stty start undef
stty stop undef

# Start nnn with your preferred options
nnn "$@"
