#!/usr/bin/env bash

# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Run xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after 60 seconds, undim if user becomes active` \
  --timer 60 \
    'xrandr --output VGA-1 --gamma 1.0:0.88:0.76 --brightness 0.25;' \
    'xrandr --output VGA-1 --gamma 1.0:0.88:0.76 --brightness 0.85;' \
  `# Undim & lock after 10 more seconds` \
  --timer 10 \
    'xrandr --output VGA-1 --gamma 1.0:0.88:0.76 --brightness 0.85; slock' \
    '' \
  `# Finally, suspend an hour after it locks` \
  --timer 3600 \
    'loginctl hibernate' \
    ''
